/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_hasakiii_util_SYNUtil */

#ifndef _Included_cn_hasakiii_util_SYNUtil
#define _Included_cn_hasakiii_util_SYNUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hasakiii_util_SYNUtil
 * Method:    getStruct
 * Signature: (Lcn/hasakiii/util/AttackInfo;Ljava/lang/String;II)Lcn/hasakiii/util/AttackInfo;
 */
JNIEXPORT jobject JNICALL Java_cn_hasakiii_util_SYNUtil_getStruct
  (JNIEnv *, jobject, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
